en:
  languageName: "English"
  weight: 1
  taxonomies:
    category: categories
    tag: tags
    series: series
  # menu: can add back once blog posts are active
  #   main:
  #   - name: Tags
  #     url: tags/
  #     weight: 10
  #     identifier: tags