en:
  languageName: "English"
  weight: 1
  taxonomies:
    category: categories
    tag: tags
    series: series
  menu:
    main:
    - name: Tags
      url: tags/
      weight: 10
      identifier: tags