en:
  languageName: "English"
  weight: 1
  taxonomies:
    category: categories
    tag: tags
    series: series
  menu:
    main:
    - name: Archive
      url: archives
      weight: 5
      identifier: fas fa-message
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10